# Generated by Django 3.2.6 on 2021-08-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='num',
            field=models.FloatField(),
        ),
    ]
